"""Claim verification interfaces for EigenTruth control pipelines."""

from __future__ import annotations

from eigentruth.verify.cache import (
    CachedVerifier,
    JsonTraceCache,
    TraceCacheRecord,
    VerifierCacheStats,
    stable_cache_key,
    verifier_cache_key,
)
from eigentruth.verify.citations import (
    CitationRecord,
    CitationVerifier,
    extract_citation_references,
)
from eigentruth.verify.claims import (
    ClaimExtractor,
    SentenceClaimExtractor,
    claim_entity_candidates,
    claim_features,
    enrich_claims_with_triples,
    extract_calculation,
    extract_claims,
)
from eigentruth.verify.coherence import (
    ClaimCoherenceIssue,
    ClaimCoherenceReport,
    ClaimDependency,
    apply_claim_coherence,
    infer_claim_dependencies,
)
from eigentruth.verify.composite import CompositeVerifier, RoutedVerifier, VerifierRoute
from eigentruth.verify.counterfactual import (
    CounterfactualProbe,
    CounterfactualProbeGenerator,
    CounterfactualProbeResult,
    CounterfactualVerificationAuditor,
    CounterfactualVerificationReport,
    audit_counterfactual_verification,
    generate_counterfactual_probes,
)
from eigentruth.verify.evidence_alignment import (
    EvidenceAlignmentEvidence,
    EvidenceAlignmentPolicy,
    EvidenceAlignmentRecord,
    EvidenceAlignmentReport,
    EvidenceAlignmentVerifier,
    audit_evidence_alignment,
)
from eigentruth.verify.groundedness import (
    EvidenceDocument,
    EvidenceQualityAssessment,
    EvidenceQualityPolicy,
    EvidenceQualitySummary,
    GroundednessVerifier,
    assess_evidence_quality,
    summarize_evidence_quality,
)
from eigentruth.verify.localization import (
    ClaimRiskLocalizationReport,
    ClaimRiskSpan,
    localize_claim_risk_spans,
)
from eigentruth.verify.perturbation import (
    PerturbationConsistencyPolicy,
    PerturbationConsistencyRecord,
    PerturbationConsistencyReport,
    PerturbationConsistencyVerifier,
    PerturbationVariant,
    audit_perturbation_consistency,
)
from eigentruth.verify.planning import (
    ClaimVerificationPlan,
    ClaimVerificationPlanner,
    VerificationBudgetPolicy,
    VerificationEscalationPolicy,
    VerificationPlanCostEstimate,
    VerificationRouteHint,
    budget_verification_plan,
    escalate_uncertain_verification_plan,
    estimate_verification_plan_cost,
)
from eigentruth.verify.protocols import Claim, VerificationResult, VerificationStatus, Verifier
from eigentruth.verify.routing import default_routed_verifier, default_verifier_routes
from eigentruth.verify.rules import InMemoryVerifier, normalize_claim_text
from eigentruth.verify.search_planning import (
    SOURCE_FAMILY_NAMES,
    CitationSearchQueryPlan,
    SourceFamilyPlan,
    clean_search_query,
    extract_entity_candidates,
    extract_keyword_terms,
    plan_citation_search_query,
    plan_source_families,
    sanitize_search_query,
)
from eigentruth.verify.selfcheck import (
    FactSelfConsistencyReport,
    FactSelfConsistencyTripleReport,
    FactSelfConsistencyVerifier,
    SelfConsistencyVerifier,
)
from eigentruth.verify.triples import (
    ClaimTriple,
    ClaimTripleExtractor,
    CompositeTripleExtractor,
    LookupTripleExtractor,
    RegexTripleExtractor,
    RegexTriplePattern,
    RuleBasedTripleExtractor,
    TripleEvidenceAudit,
    TripleEvidenceAuditReport,
    TripleEvidenceVerifier,
    TripleSlotEvidence,
    audit_claim_triples,
    extract_claim_triples,
)

__all__ = [
    "CachedVerifier",
    "Claim",
    "ClaimCoherenceIssue",
    "ClaimCoherenceReport",
    "ClaimDependency",
    "ClaimExtractor",
    "ClaimRiskLocalizationReport",
    "ClaimRiskSpan",
    "CitationRecord",
    "CitationSearchQueryPlan",
    "CitationVerifier",
    "ClaimTriple",
    "ClaimTripleExtractor",
    "ClaimVerificationPlan",
    "ClaimVerificationPlanner",
    "CompositeTripleExtractor",
    "CompositeVerifier",
    "CounterfactualProbe",
    "CounterfactualProbeResult",
    "CounterfactualProbeGenerator",
    "CounterfactualVerificationAuditor",
    "CounterfactualVerificationReport",
    "EvidenceAlignmentEvidence",
    "EvidenceAlignmentPolicy",
    "EvidenceAlignmentRecord",
    "EvidenceAlignmentReport",
    "EvidenceAlignmentVerifier",
    "EvidenceDocument",
    "EvidenceQualityAssessment",
    "EvidenceQualityPolicy",
    "EvidenceQualitySummary",
    "FactSelfConsistencyReport",
    "FactSelfConsistencyTripleReport",
    "FactSelfConsistencyVerifier",
    "GroundednessVerifier",
    "InMemoryVerifier",
    "JsonTraceCache",
    "LookupTripleExtractor",
    "PerturbationConsistencyPolicy",
    "PerturbationConsistencyRecord",
    "PerturbationConsistencyReport",
    "PerturbationConsistencyVerifier",
    "PerturbationVariant",
    "RegexTripleExtractor",
    "RegexTriplePattern",
    "RuleBasedTripleExtractor",
    "RoutedVerifier",
    "TraceCacheRecord",
    "TripleEvidenceAudit",
    "TripleEvidenceAuditReport",
    "TripleEvidenceVerifier",
    "TripleSlotEvidence",
    "VerificationResult",
    "VerificationStatus",
    "VerificationBudgetPolicy",
    "VerificationEscalationPolicy",
    "VerifierCacheStats",
    "Verifier",
    "VerifierRoute",
    "VerificationPlanCostEstimate",
    "VerificationRouteHint",
    "SentenceClaimExtractor",
    "SelfConsistencyVerifier",
    "SOURCE_FAMILY_NAMES",
    "SourceFamilyPlan",
    "apply_claim_coherence",
    "audit_counterfactual_verification",
    "audit_evidence_alignment",
    "audit_perturbation_consistency",
    "assess_evidence_quality",
    "generate_counterfactual_probes",
    "audit_claim_triples",
    "claim_entity_candidates",
    "claim_features",
    "clean_search_query",
    "default_routed_verifier",
    "default_verifier_routes",
    "enrich_claims_with_triples",
    "extract_calculation",
    "extract_citation_references",
    "extract_claims",
    "extract_claim_triples",
    "extract_entity_candidates",
    "extract_keyword_terms",
    "localize_claim_risk_spans",
    "budget_verification_plan",
    "escalate_uncertain_verification_plan",
    "estimate_verification_plan_cost",
    "infer_claim_dependencies",
    "normalize_claim_text",
    "plan_citation_search_query",
    "plan_source_families",
    "sanitize_search_query",
    "stable_cache_key",
    "summarize_evidence_quality",
    "verifier_cache_key",
]
